import org.apache.pivot.collections.ArrayList as PivotArrayList

class PModel {
    PivotArrayList<String> states = new PivotArrayList<String>()

    PModel() {
        states.comparator = String.CASE_INSENSITIVE_ORDER
        states << "Alabama"
        states << "Alaska"
        states << "Arizona"
        states << "Arkansas"
        states << "California"
        states << "Colorado"
        states << "Connecticut"
        states << "Delaware"
        states << "District of Columbia"
        states << "Florida"
        states << "Georgia"
        states << "Hawaii"
        states << "Idaho"
        states << "Illinois"
        states << "Indiana"
        states << "Iowa"
        states << "Kansas"
        states << "Kentucky"
        states << "Louisiana"
        states << "Maine"
        states << "Maryland"
        states << "Massachusetts"
        states << "Michigan"
        states << "Minnesota"
        states << "Mississippi"
        states << "Missouri"
        states << "Montana"
        states << "Nebraska"
        states << "Nevada"
        states << "New Hampshire"
        states << "New Jersey"
        states << "New Mexico"
        states << "New York"
        states << "North Carolina"
        states << "North Dakota"
        states << "Ohio"
        states << "Oklahoma"
        states << "Oregon"
        states << "Pennsylvania"
        states << "Rhode Island"
        states << "South Carolina"
        states << "South Dakota"
        states << "Tennessee"
        states << "Texas"
        states << "Utah"
        states << "Vermont"
        states << "Virginia"
        states << "Washington"
        states << "West Virginia"
        states << "Wisconsin"
        states << "Wyoming"
    }
}
